#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="vtiger%20CRM%206.3.0/Core%20Product/vtigercrm6.3.0.tar.gz"
URL="http://downloads.sourceforge.net/project/vtigercrm/$VERSION"

dl $URL /usr/local/src

