#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="7.1.0"
BASE_URL="http://downloads.sourceforge.net/project/vtigercrm"
URL="${BASE_URL}/vtiger%20CRM%20${VERSION}/Core%20Product/vtigercrm${VERSION}.tar.gz"

dl $URL /usr/local/src
