#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="vtiger%20CRM%205.4.0/Core%20Product/vtigercrm-5.4.0.tar.gz"
URL="http://sourceforge.net/projects/vtigercrm/files/$VERSION"

dl $URL /usr/local/src

