#!/bin/bash -ex

ADMIN_MAIL=admin@example.com
ADMIN_PASS=turnkey

DB_NAME=vtigercrm
DB_USER=vtigercrm
DB_PASS=$(mcookie)

WEBROOT=/var/www/vtigercrm

# unpack tarball to webroot and set permissions
tar -zxf /usr/local/src/vtigercrm*.tar.gz -C /var/www/
rm -f /usr/local/src/vtigercrm*

chown -R root:root $WEBROOT
for i in config.inc.php tabdata.php parent_tabdata.php backup cache storage user_privileges modules cron/modules test logs layouts languages; do
    chown -R www-data:www-data $WEBROOT/$i
done

# vtiger recommended php settings
CONF=/etc/php5/apache2/php.ini
updateconf() {
    sed -i "s|$1 = \(.*\)|$1 = $2|" $CONF
}

updateconf allow_call_time_pass_reference On
updateconf max_execution_time 600
updateconf memory_limit 128M
updateconf display_errors On
updateconf log_errors Off
updateconf error_reporting "E_WARNING \& ~E_NOTICE \& ~E_DEPRECATED"
updateconf short_open_tag On
sed -i "s|^; max_input_vars.*|max_input_vars = 1500|" $CONF

# convenience execution variables
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# start mysql
/etc/init.d/mysql start

# create database
$MYSQL_ADMIN create $DB_NAME

# create database user with privileges on the database
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# update apache configuration
a2dissite 000-default
a2ensite vtigercrm

# vtiger configuration
/etc/init.d/apache2 start

cat << EOF > /tmp/vtiger.twill
go http://127.0.0.1/index.php

fv 2 1 nop
submit
fv 2 1 nop
submit
fv 2 1 nop
submit

fv 2 db_hostname localhost
fv 2 db_username $DB_USER
fv 2 db_password $DB_PASS
fv 2 db_name $DB_NAME
fv 2 password $ADMIN_PASS
fv 2 retype_password $ADMIN_PASS
fv 2 admin_email $ADMIN_MAIL
submit

fv 2 1 nop
submit

fv 2 industry Other
submit

EOF

twill-sh /tmp/vtiger.twill
rm -f /tmp/vtiger.twill

# set local smtp server
$MYSQL_BATCH --execute "USE $DB_NAME; INSERT INTO vtiger_systems (id, server, server_port, server_username, server_password, server_type, smtp_auth, server_path, from_email_field) VALUES ('1', '127.0.0.1', '25', NULL, NULL, 'email', 'false', NULL, NULL);"

# make site_url dynamic
CONF=$WEBROOT/config.inc.php
sed -i "s|\$site_URL = \(.*\)|\$site_URL = 'http://'.\$_SERVER['HTTP_HOST'];|" $CONF

# stop services
/etc/init.d/apache2 stop
/etc/init.d/mysql stop

