#!/bin/bash -e
# regenerate vtiger secrets

. /etc/default/inithooks

WEBROOT=/var/www/vtigercrm

PASSWORD=$(mcookie)
UNIQUE_KEY=$(mcookie)
ACCESS_KEY=$(mcookie | cut --bytes 1-21)

updateconf() {
    sed -i "s|$1 = \(.*\)|$1 = '$2';|" $WEBROOT/config.inc.php
}

updateconf "\['db_password'\]" $PASSWORD
updateconf "application_unique_key" $UNIQUE_KEY

CONF=$WEBROOT/user_privileges/user_privileges_1.php
sed -i "s|'accesskey'=>'\([A-Za-z0-9]*\)'|'accesskey'=>'$ACCESS_KEY'|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=vtigercrm --pass="$PASSWORD" \
    --query="UPDATE vtigercrm.vtiger_users SET accesskey=\"$ACCESS_KEY\" WHERE id=1;"

